# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\matej\PycharmProjects\omega\script\Main\Kategorie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from script.Main.Zanry.Klasicke import Ui_Klasik
from script.Main.Zanry.Hymna import Ui_Hymna
from script.Main.Zanry.Country import Ui_Country
from script.Main.Zanry.Koledy import Ui_Koledy
from script.Main.Zanry.Jazz import Ui_Jazz
from script.Main.Zanry.Pohadky import Ui_Pohadky
class Ui_Form(object):
    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Klasik()
        self.ui.setupUi( self.window)
        self.window.show()
    def openWindow1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Hymna()
        self.ui.setupUi( self.window)
        self.window.show()
    def openWindow2(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Country()
        self.ui.setupUi(self.window, parent=Form)
        self.window.show()

    def openWindow3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Koledy()
        self.ui.setupUi( self.window)
        self.window.show()

    def openWindow4(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Jazz()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindow5(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Pohadky()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(681, 533)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(Form,clicked=lambda:self.openWindow())
        self.pushButton.setGeometry(QtCore.QRect(-10, 0, 701, 111))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form,clicked=lambda:self.openWindow2())
        self.pushButton_2.setGeometry(QtCore.QRect(-10, 110, 701, 111))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form,clicked=lambda:self.openWindow3())
        self.pushButton_3.setGeometry(QtCore.QRect(-10, 220, 701, 111))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form,clicked=lambda:self.openWindow4())
        self.pushButton_4.setGeometry(QtCore.QRect(-10, 320, 701, 111))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form,clicked=lambda:self.openWindow1())
        self.pushButton_5.setGeometry(QtCore.QRect(-10, 430, 701, 111))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form, clicked=lambda: self.openWindow5())
        self.pushButton_6.setGeometry(QtCore.QRect(-10, 430, 701, 111))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kategorie"))
        self.pushButton.setText(_translate("Form", "Klasicke"))
        self.pushButton_2.setText(_translate("Form", "Country"))
        self.pushButton_3.setText(_translate("Form", "Koledy"))
        self.pushButton_4.setText(_translate("Form", "Jazz"))
        self.pushButton_5.setText(_translate("Form", "Hymny"))
        self.pushButton_6.setText(_translate("Form", "Pohadky"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
