# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\matej\PycharmProjects\omega\script\Main\Hymna.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from script.Main.SONGY.KdeDomov import Ui_Kdedomov

class Ui_Hymna(object):
    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Kdedomov()
        self.ui.setupUi( self.window)
        self.window.show()
        self.hide()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(581, 407)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(20, 60, 185, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Form,clicked=lambda:self.openWindow())
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 20, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(20, 140, 185, 41))
        self.commandLinkButton_4.setText("")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(Form)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(20, 100, 185, 41))
        self.commandLinkButton_3.setText("")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hymna"))
        self.commandLinkButton_2.setText(_translate("Form", "Pod Tatrou sa blizka"))
        self.commandLinkButton.setText(_translate("Form", "Kde domov můj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Hymna()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
