# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Klobouk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Klobouk(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(714, 763)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"border-color: rgb(255, 255, 255);")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 241, 301))
        self.label_3.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"gridline-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(330, 100, 310, 400))
        self.treeWidget.setStyleSheet(
            "background-color: rgb(209, 209, 209);\n""background-image: url(C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy2.png);")
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.setIndentation(1)

        header = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.headerItem().setText(0, "Akordy")
        label = QtWidgets.QLabel()
        pixmap = QtGui.QPixmap('C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy2.png')
        label.setPixmap(pixmap)
        self.treeWidget.setItemWidget(header, 0, label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Klobouk ve křoví"))
        self.label_2.setText(_translate("Form", "Jan Werich, Jiří Voskovec"))
        self.label.setText(_translate("Form", "Klobouk ve křoví"))
        self.label_3.setText(_translate("Form", " C    Fmi                    Fmi    C\n"
"Vítr vane pouští,  po písku žene klobouk,\n"
" Fmi   G      C/Ami   Fmi     G         C \n"
"zahnal ho do houští, starý a černý klobouk.\n"
"\n"
" C    Fmi                    Fmi    C\n"
"Kdepak je ta hlava,   která klobouk nosila?\n"
" Fmi   G      C/Ami   Fmi     G         C\n"
"Byla černá či plavá?  Komu asi patřila?\n"
"\n"
" C    Fmi                    Fmi    C\n"
"Kdo to v poušti zmizel?  Odkud šel a kam?\n"
" Fmi   G      C/Ami   Fmi     G         C \n"
"Jaký to měl svízel, že byl v poušti sám?\n"
"\n"
" C    Fmi                    Fmi    C  \n"
"Jen zaváté stopy.  Starý klobouk ve křoví.\n"
" Fmi   G      C/Ami   Fmi     G         C\n"
"Nikdo nic nepochopí.  Nikdo se nic nedoví."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Klobouk()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
