# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Purpura.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Purpura(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(711, 761)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 300, 311))
        self.label_3.setStyleSheet("background-color: rgb(104, 104, 104);\n"
                                   "gridline-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 91, 31))
        self.label_2.setObjectName("label_2")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(330, 80, 310, 590))
        self.treeWidget.setStyleSheet(
            "background-color: rgb(209, 209, 209);\n""background-image: url(C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy1.png);")
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.setIndentation(1)

        header = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.headerItem().setText(0, "Akordy")
        label = QtWidgets.QLabel()
        pixmap = QtGui.QPixmap('C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy1.png')
        label.setPixmap(pixmap)
        self.treeWidget.setItemWidget(header, 0, label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Purpura"))
        self.label.setText(_translate("Form", "Purpura"))
        self.label_3.setText(_translate("Form", "Es                              As              Es\n"
"Tiše a ochotně purpura na plotně voní, stále voní,\n"
"                                      B7  As   Fmi B7\n"
"nikdo si nevšímá, jak život mění se v dým.\n"
"\n"
"Es                                       As           Es\n"
"Snad jenom v podkroví básníci bláhoví pro ni slzy roní,\n"
"                    B7               Es As  Es Es7\n"
"hrany jí odzvoní rampouchem křišťálovým.\n"
"\n"
"As                                         Es\n"
"Slunce se vynoří, hned však se k pohoří skloní, rychle skloní,\n"
"  Cmi                 F       F7  B     As    B7\n"
"a pak se dostaví dlouhá a pokojná noc.\n"
"\n"
"Es                               As              Es\n"
"Tiše a ochotně purpura na plotně voní, stále voní,\n"
"                          B7              Es  As  Es\n"
"po ní k nám vklouzlo to tajemné kouzlo vánoc."))
        self.label_2.setText(_translate("Form", "Vánoční koledy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Purpura()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
