# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\matej\PycharmProjects\omega\script\Main\SeverniVitr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Severni(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(714, 722)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 260, 620))
        self.label_3.setStyleSheet("background-color: rgb(104, 104, 104);\n"
                                   "gridline-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(330, 100, 310, 400))
        self.treeWidget.setStyleSheet(
            "background-color: rgb(209, 209, 209);\n""background-image: url(C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy8.png);")
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.setIndentation(1)

        header = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.headerItem().setText(0, "Akordy")
        label = QtWidgets.QLabel()
        pixmap = QtGui.QPixmap('C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordy8.png')
        label.setPixmap(pixmap)
        self.treeWidget.setItemWidget(header, 0, label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Severní vítr"))
        self.label_3.setText(_translate("Form", "   D                    Hmi\n"
"1. Jdu s děravou patou, mám horečku zlatou,\n"
"        G                     D\n"
"   jsem chudý, jsem sláb, nemocen.\n"
"                   Hmi               G\n"
"   Hlava mě pálí a v modravé dáli se leskne\n"
"     A7         D\n"
"   a třpytí můj sen.\n"
"   \n"
"        D                   Hmi \n"
"2. Kraj pod sněhem mlčí, tam stopy jsou vlčí, \n"
"       G                  D  \n"
"   tam zbytečně budeš mi psát,\n"
"                      Hmi                \n"
"   sám v dřevěné boudě sen o zlaté hroudě\n"
"      G       A7         D\n"
"   já nechám si tisíckrát zdát.\n"
"\n"
"   D       D7        G     D                A7\n"
"R: Severní vítr je krutý, počítej lásko má s tím, \n"
"    D          D7        G             D     A7     D A7\n"
"   k nohám Ti dám zlaté pruty, nebo se vůbec nevrátím\n"
"\n"
"      D                       Hmi\n"
"3. Tak zarůstám vousem a vlci už jdou sem,\n"
"      G                      D\n"
"   už slyším je výt blíž a blíž.\n"
"                        Hmi              \n"
"   Už mají mou stopu, už větří, že kopu\n"
"    G          A7               D\n"
"   svůj hrob a že stloukám si kříž.\n"
"\n"
"     D                     Hmi\n"
"4. Zde leží ten blázen, chtěl dům a chtěl bazén\n"
"     G                     D\n"
"   a opustil tvou krásnou tvář.\n"
"                        Hmi               \n"
"   Má plechovej hrnek a pár zlatejch zrnek\n"
"    G        A7           D     \n"
"   a nad hrobem polární zář.\n"
"\n"
"   D       D7         G     D               A7\n"
"R: Severní vítr je krutý, počítej lásko má s tím, \n"
"    D          D7        G              D    A7    D A7\n"
"   k nohám Ti dám zlaté pruty, nebo se vůbec nevrátím\n"
"\n"
"      D        D7        G             D     A7    D \n"
"   k nohám Ti dám zlaté pruty, nebo se vůbec nevrátím"))
        self.label.setText(_translate("Form", "Severní vítr"))
        self.label_2.setText(_translate("Form", "Zdeněk Svěrák, Jaroslav Uhlíř"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Severni()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
