# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ukol.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(711, 764)
        Form.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 300, 311))
        self.label_3.setStyleSheet("background-color: rgb(104, 104, 104);\n"
                                   "gridline-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(330, 100, 310, 400))
        self.treeWidget.setStyleSheet(
            "background-color: rgb(209, 209, 209);\n""background-image: url(C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordz.png);")
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.setIndentation(1)

        header = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.headerItem().setText(0, "Akordy")
        label = QtWidgets.QLabel()
        pixmap = QtGui.QPixmap('C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\akordz.png')
        label.setPixmap(pixmap)
        self.treeWidget.setItemWidget(header, 0, label)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bláznova ukolébavka"))
        self.label.setText(_translate("Form", "Bláznova ukolébavka"))
        self.label_2.setText(_translate("Form", "táborové písně"))
        self.label_3.setText(_translate("Form", "   D               A           G              D\n"
"1. Máš, má ovečko, dávno spát, už píseň ptáků končí,\n"
"                   A             G         D   \n"
"   kvůli nám přestal i vítr vát, jen můra zírá zvenčí,\n"
"    A                   G   \n"
"   já znám její zášť, tak vyhledej skrýš,\n"
"    A                  G       A\n"
"   zas má bílej plášť a v okně je mříž.\n"
"\n"
"    D              A\n"
"R: Máš, má ovečko, dávno spát,\n"
"   G                   E   \n"
"   a můžeš hřát, ty mě můžeš hřát,\n"
"         D         G                D          G \n"
"   vždyť přijdou se ptát, zítra zas přijdou se ptát,\n"
"               D           G       D\n"
"   jestli ty v mých představách už mizíš.\n"
"\n"
"2. Máš, má ovečko, dávno spát, už máme půlnoc temnou,\n"
"   zítra budou nám bláznů lát, že ráda snídáš se mnou,\n"
"   proč měl bych jim lhát, že jsem tady sám,\n"
"   když tebe mám rád, když tebe tu mám.\n"
"\n"
"R:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
