from PyQt5 import QtCore, QtGui, QtWidgets
from script.Main.akordy.C import Ui_C

class Ui_Akordy(object):
    def openSettingsWindow(self):
        self.settingsWindow = QtWidgets.QMainWindow()
        self.settingsUi = Ui_C()
        self.settingsUi.setupUi(self.settingsWindow)
        self.settingsWindow.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(942, 669)
        MainWindow.setStyleSheet("background-color: rgb(125, 125, 125);\n"
                           "border-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, -10, 371, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 70, 341, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 10, 341, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 541, 541))
        self.label_2.setStyleSheet("background-image: url(C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\kytara.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\matej\\PycharmProjects\\omega\\script\\Main\\pics\\kytara.png"))

        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menubar.setObjectName("menubar")
        self.menuAkordy_C = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_C.setObjectName("menuAkordy_C")
        self.menuAkordy_Cis_Des = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_Cis_Des.setObjectName("menuAkordy_Cis_Des")
        self.menuAkordy_D = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_D.setObjectName("menuAkordy_D")
        self.menuAkordy_Dis_Es = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_Dis_Es.setObjectName("menuAkordy_Dis_Es")
        self.menuAkordy_E = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_E.setObjectName("menuAkordy_E")
        self.menuAkordy_F = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_F.setObjectName("menuAkordy_F")
        self.menuAkordy_Fis_Ges = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_Fis_Ges.setObjectName("menuAkordy_Fis_Ges")
        self.menuAkordy_G = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_G.setObjectName("menuAkordy_G")
        self.menuAkordy_Gis_As = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_Gis_As.setObjectName("menuAkordy_Gis_As")
        self.menuAkordy_A = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_A.setObjectName("menuAkordy_A")
        self.menuAkordy_B_Ais = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_B_Ais.setObjectName("menuAkordy_B_Ais")
        self.menuAkordy_H = QtWidgets.QMenu(self.menubar)
        self.menuAkordy_H.setObjectName("menuAkordy_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuAkordy_C.addSeparator()
        self.menubar.addAction(self.menuAkordy_C.menuAction())
        self.menubar.addAction(self.menuAkordy_Cis_Des.menuAction())
        self.menubar.addAction(self.menuAkordy_D.menuAction())
        self.menubar.addAction(self.menuAkordy_Dis_Es.menuAction())
        self.menubar.addAction(self.menuAkordy_E.menuAction())
        self.menubar.addAction(self.menuAkordy_F.menuAction())
        self.menubar.addAction(self.menuAkordy_Fis_Ges.menuAction())
        self.menubar.addAction(self.menuAkordy_G.menuAction())
        self.menubar.addAction(self.menuAkordy_Gis_As.menuAction())
        self.menubar.addAction(self.menuAkordy_A.menuAction())
        self.menubar.addAction(self.menuAkordy_B_Ais.menuAction())
        self.menubar.addAction(self.menuAkordy_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Přehled Akordů"))
        self.menuAkordy_C.setTitle(_translate("MainWindow", "Akordy: C"))
        self.menuAkordy_Cis_Des.setTitle(_translate("MainWindow", "Akordy: Cis Des"))
        self.menuAkordy_D.setTitle(_translate("MainWindow", "Akordy: D"))
        self.menuAkordy_Dis_Es.setTitle(_translate("MainWindow", "Akordy: Dis Es"))
        self.menuAkordy_E.setTitle(_translate("MainWindow", "Akordy: E"))
        self.menuAkordy_F.setTitle(_translate("MainWindow", "Akordy: F"))
        self.menuAkordy_Fis_Ges.setTitle(_translate("MainWindow", "Akordy: Fis Ges"))
        self.menuAkordy_G.setTitle(_translate("MainWindow", "Akordy: G"))
        self.menuAkordy_Gis_As.setTitle(_translate("MainWindow", "Akordy Gis As"))
        self.menuAkordy_A.setTitle(_translate("MainWindow", "Akordy: A"))
        self.menuAkordy_B_Ais.setTitle(_translate("MainWindow", "Akordy: B Ais"))
        self.menuAkordy_H.setTitle(_translate("MainWindow", "Akordy H"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
